### ISSUE TITLE
FFT Choice in dirty_image_generate

### ISSUE THREAD

**Issue by piyanatk** [miguelfmorales/FHD#28]
Is there a physical reason to use forward FFT (normalizer=1/N, negative exponent) in dirty_image_generate?

If you visibility is generated from other programing languages that is not IDL, the normalization and sign convention in the FFT can be incompatible. For example, FFTW3 (C/C++) has the same sign convention as in IDL FFT but does not apply 1/N normalization to both the forward and the backward transform, and Python (Numpy and Scipy) FFT also use the same sign convention but apply the 1/N normalization on the backward transform (opposite to IDL).

**Comment by adampbeardsley** [comment]
Ian can correct me if I'm wrong, but I'm pretty sure the FFTs in FHD should now have normalizations based on units (for example, Jy/str in the sky maps to Jy visibilities). So even though IDL includes the 1/N for the FFT, other factors should be included to make the units work and thus the internal convention is irrelevant.

**Comment by piyanatk** [comment]
@adampbeardsley Are you saying that the transform should be correct as long as the unit of the visibility is Jy?

**Comment by adampbeardsley** [comment]
Ah, now I see what you're worried about. I think this has to do with the offline conversation we were having. I think that the output fits images are normalized post-FFT such that a point source of 1 Jy will be seen with a peak 1 Jy/beam. This is done on line 70 (IF keyword_set(normalization)...). 
But now I think I'm getting beyond my actual understanding of FHD's normalization. @isullivan ?

**Comment by piyanatk** [comment]
Well, first at line 67
```
IF Keyword_Set(degpix) THEN di_uv_use/=(degpix*!DtoR)^2. ;FFT normalization
```
If I understand correctly the uv is divided by `(degpix*!DtoR)^2` to convert the FFT normalization factor `1/N^2` from the unit of 1/pixel^2 to 1/rad^2. This is necessary to make the flux unit be Jy/sr.

If you are right about line 70, then the flux unit is converted from Jy/sr to Jy/beam there.

**Comment by isullivan** [comment]
The reason for the choice of FFT convention in FHD is that the forward transform is slightly more efficient in IDL when transforming from the u-v plane to real-valued image space. The normalization has been worked out so that a 1 Jy source at the image center is modeled by an array of all 1s in the u-v plane and has visibilities of all 1s after degridding. The gridded visibilities (in the u-v plane) are in units of variance-weighted Janskys, which is not compatible with other software that grids visibilities and is not meant to be. The output from the FFT wraper function dirty_image_generate.pro is an image of the sky with units of Jy/pixel (the factor of [degpix*!DtoR]^2 accounts for the units of the Fourier transform), and the function get_image_renormalization.pro calculates the conversion factor between Jy/pixel and Jy/beam.
