### ISSUE TITLE
Holes in residual decon diffuse maps

### ISSUE THREAD

**Issue by nicholebarry** [miguelfmorales/FHD#35]
Deconvolution is leaving behind holes in the residual images, causing the diffuse maps to appear pitted. I'm not sure what this is indicative of, but something might be wrong. This issue seems to be consistent, regardless of whether the deconvolution that made the diffuse maps was a regular test, a regular test without the time cut, a test of four polarizations, or a test of four polarizations that fit fluxes in all four.

I'm classifying this problem as separate from potential polarization problems.

![i_eor0_polarized_diffuse_zenith_4pol_allfluxfit](https://cloud.githubusercontent.com/assets/5588290/11612362/78d88eba-9bab-11e5-8734-7ee3d29d2b75.png)

Attached is a representative grid out file
[firstpass.o65316.15_decon.txt](https://github.com/miguelfmorales/FHD/files/53089/firstpass.o65316.15_decon.txt)

Attached is a representative settings file
[1061317152_settings.txt](https://github.com/miguelfmorales/FHD/files/53090/1061317152_settings.txt)

**Comment by nicholebarry** [comment]
The apparent holes are much different than what we had before when Adam ran the diffuse code. Here is a diffuse image using the same obsids and on the same scale of Adam's run over a year ago.

Clustered holes are much less in Adam's run. There is a little bit of confusion as to how Adam generated his. He thinks it's from a deconvolution run, but it could also be from a decon->firstpass run. 

![eor0_diffuse_model_94](https://cloud.githubusercontent.com/assets/5588290/12140576/f690911a-b41d-11e5-93da-2bec96e11656.png)

**Comment by nicholebarry** [comment]
Ian found a potential refraction bug, which applied refraction effects 2x. This will be a small effect, but will move source location slightly. Here is the deconvolution diffuse map for the zenith pointing.

![eor0_diffuse_refract](https://cloud.githubusercontent.com/assets/5588290/12758608/f802cab6-c991-11e5-8e89-cf2c07518021.png)

Clusters of holes have become "tighter," indicating an improvement. However, hole clusters still do exist, which is in contrast to Adam's old diffuse map.

Here is the PS difference between no diffuse map in calibration or modeling and the updated diffuse map above in both calibration and modeling. There are obvious improvements, which indicates that new diffuse maps are not *bad*, per se.
![fhd_nb__nodiffuse_jan2016_obs_id_6176_minus_diffuse_i_jan2016_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/12759006/cf38e7a8-c993-11e5-870f-e12be5ea356d.png)

**Comment by adampbeardsley** [comment]
Sorry for the late arrival, but I wanted to correct one small thing Nichole mentioned back on Jan 6. The diffuse model she showed (EoR0_diffuse_model_94), and I think has been in the git repo for a while, was actually created from a firstpass run, not from a deconvolution run. It was meant to be a placeholder until a better model came along, so the documentation isn't great. Here's the info I have on it:
Created from the run std_Dec2014b (a firstpass run from early December, 2014). 
Here's a settings file from that run: [1061312640_settings.txt](https://github.com/miguelfmorales/FHD/files/114431/1061312640_settings.txt)
Then, I think because I needed a uniform-weighted image rather than natural weighted, I needed to use a script to call combine_obs (located at ~beards/MWA/IDL_code/custom_utils/hack_combine_obs.pro on the mit cluster). It's been reused for other purposes, so some of the hard-coded parameters are different now.
Finally, I combined XX and YY to form a pseudo-stokes I (this is the part that was meant to be improved on short order, and why I didn't bother to put too much effort into documentation).
residual I ~ (dirty XX - model XX + dirty YY - model YY) / (weights XX + weights YY)

I don't have any idea about the holes, or lack thereof, but I just wanted to clear up the diffuse model.

**Comment by isullivan** [comment]
After some discussion, we think this issue should be closed. There have been numerous changes between these runs, particularly with the beam model and an important polarization fix, and these runs were done in a slightly different fashion.
